[tool.poetry]
name = "titanic-analysis"
authors = ["sjb0331 <password13579@naver.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.0"
numpy = "^1.21.0"
matplotlib = "^3.4.0"
seaborn = "^0.11.0"
scikit-learn = "^0.24.0"
networkx = "^2.5"